### ISSUE TITLE
PBI 5 - As a backend engineer, I want to design database schema for party information data

### ISSUE THREAD

**Issue by MedhaNaik** [sanjanaluri/PartyHolic#6]
- [x] Assuming backend is set up,
- [x] create schema and empty table creation on server init
- [x] create methods for populating new entries for party list
- [x] send party list for given user and given geolocation - for 10 mile radius

all outputs will be in json format.

**Comment by Himakireeti** [comment]
party table
CREATE TABLE "untitled_table_1" ("party_id" int NOT NULL,"party_name" text NOT NULL,"host_id" int NOT NULL,"address_id" int NOT NULL,"start_time" datetime NOT NULL,"end_time" datetime,"tag_id" text,"party_description" text,"image_id" int,"attendee_count" int, PRIMARY KEY (party_id), FOREIGN KEY("address_id") REFERENCES address_table(address_id), FOREIGN KEY("host_id") REFERENCES user_table(user_id));

address table
CREATE TABLE “address_table” ("line_one" text NOT NULL,"line_two" text,"city" text NOT NULL,"state" text NOT NULL,"zipcode" int NOT NULL,"latitude" num NOT NULL,"longitude" num NOT NULL,"address_id" int NOT NULL,"country" text NOT NULL, PRIMARY KEY (address_id));

user table
CREATE TABLE “user_table” ("user_id" integer NOT NULL,"user_name" text NOT NULL,"default_address_id" text NOT NULL,"gender" text NOT NULL,"bio" text,"photo_id" text, PRIMARY KEY (user_id));

tag table
CREATE TABLE "untitled_table_4" ("tag_id" integer,"tag_name" text, PRIMARY KEY (id));
